language: minimal

services: docker

before_install:
  - docker -v

install:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed phatryo99/udagram-api-feed:v1
  - docker tag udagram-api-user phatryo99/udagram-api-user:v1
  - docker tag udagram-frontend phatryo99/udagram-frontend:v1
  - docker tag udagram-reverseproxy phatryo99/udagram-reverseproxy:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push phatryo99/udagram-api-feed:v1
  - docker push phatryo99/udagram-api-user:v1
  - docker push phatryo99/udagram-frontend:v1
  - docker push phatryo99/udagram-reverseproxy:v1
